### ISSUE TITLE
DatePicker: Example fails on MyFaces

### ISSUE THREAD

**Issue by melloware** [primefaces/showcase-facelift#69]
MyFaces 2.3.4 or 3.0.0-SNAPSHOT fails with..

```
SEVERE: iteration size cannot be greater than collection size
javax.faces.FacesException: iteration size cannot be greater than collection size
        at org.apache.myfaces.view.facelets.component.UIRepeat._validateAttributes(UIRepeat.java:962)
        at org.apache.myfaces.view.facelets.component.UIRepeat.process(UIRepeat.java:1022)
        at org.apache.myfaces.view.facelets.component.UIRepeat.encodeChildren(UIRepeat.java:1816)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:542)
        at org.primefaces.component.panelgrid.PanelGridRenderer.encodeDynamicBody(PanelGridRenderer.java:154)
        at org.primefaces.component.panelgrid.PanelGridRenderer.encodeTableBody(PanelGridRenderer.java:116)
        at org.primefaces.component.panelgrid.PanelGridRenderer.encodeTableLayout(PanelGridRenderer.java:79)
        at org.primefaces.component.panelgrid.PanelGridRenderer.encodeEnd(PanelGridRenderer.java:51)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
        at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:88)
        at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:70)
        at org.primefaces.component.dialog.DialogRenderer.encodeContent(DialogRenderer.java:202)
        at org.primefaces.component.dialog.DialogRenderer.encodeMarkup(DialogRenderer.java:125)
        at org.primefaces.component.dialog.DialogRenderer.encodeEnd(DialogRenderer.java:55)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:675)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:555)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:551)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1897)
        at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:315)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:73)
        at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:117)
        at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:266)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:206)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
        at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1583)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:494)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by melloware** [comment]
OK  the issue is in the dialog it has...

```xml
<p:panelGrid id="display" columns="4"
```

But inside it does this UI Repeat...
```xml
                    <h:outputText value="Range Selection:" />
                    <ui:repeat var="date" value="#{calendarView.range}" varStatus="status" size="2">
                        #{status.first ? '' : '-'}
                        <h:outputText value="#{date}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                    </ui:repeat>
```

MyFaces does not seem to like this but I don't know whether its something Mojarra is accidentally let working or whether its a bug and MyFaces is doing the proper checking?

**Comment by tandraschko** [comment]
What exactly should it do?

**Comment by melloware** [comment]
I am not exactly sure but it the issue definitely seems related to the UI repeat.  It actually might have nothing to do with the dialog at all just the UI Repeat.

**Comment by tandraschko** [comment]
yeah, it's only related to UIRepeat.
We have some checks to catch illegal usages there:
https://github.com/apache/myfaces/blob/4a0ac351f004821e1b55c92486a952913370745b/impl/src/main/java/org/apache/myfaces/view/facelets/component/UIRepeat.java#L945

**Comment by melloware** [comment]
I see the problem i think i can fix it.  I think MyFaces is doing the right thing.

**Comment by tandraschko** [comment]
thanks!
